// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;
import {EthEscrow, ERC20Escrow, BaseEscrow, IERC20Minimal} from "../src/BaseEscrow.sol";
interface Vm { function addr(uint256) external returns(address); function sign(uint256,bytes32) external returns(uint8,bytes32,bytes32); function deal(address,uint256) external; function prank(address) external; function warp(uint256) external; function expectRevert(bytes4) external; }
contract MockToken is IERC20Minimal { mapping(address=>uint256) public balanceOf; mapping(address=>mapping(address=>uint256)) public allowance; bool public fail; bool public fee;
 function setFee(bool v) external { fee=v; } function setFail(bool v) external { fail=v; }
 function mint(address a,uint256 n) external {balanceOf[a]+=n;} function approve(address a,uint256 n) external returns(bool){allowance[msg.sender][a]=n;return true;} function transferFrom(address f,address t,uint256 n) external returns(bool){if(fail)return false;require(allowance[f][msg.sender]>=n&&balanceOf[f]>=n);allowance[f][msg.sender]-=n;balanceOf[f]-=n;uint256 got=fee?n-1:n;balanceOf[t]+=got;return true;} function transfer(address t,uint256 n) external returns(bool){if(fail)return false;require(balanceOf[msg.sender]>=n);balanceOf[msg.sender]-=n;balanceOf[t]+=n;return true;} }
contract BaseEscrowTest {
 Vm constant vm=Vm(address(uint160(uint256(keccak256("hevm cheat code")))));
 uint256 payerPk=0xA11CE; uint256 recipientPk=0xB0B; address payer; address recipient; address refund; bytes32 id=keccak256("claim"); bytes32 commitment=keccak256("secret"); EthEscrow e;
 function setUp() public {payer=vm.addr(payerPk); recipient=vm.addr(recipientPk); refund=vm.addr(0xC0FFEE); e=new EthEscrow(); vm.deal(payer,10 ether); vm.prank(payer); e.createTerms(id,refund,commitment,1 ether,block.timestamp+100,7);}
 function sig(bytes32 d,uint256 pk) internal returns(bytes memory){(uint8 v,bytes32 r,bytes32 s)=vm.sign(pk,d);return abi.encodePacked(r,s,v);}
 function fund() internal {vm.prank(payer); e.fund{value:1 ether}(id,sig(e.fundAuthorizationDigest(id),payerPk));}
 function testHappyClaim() public {setUp();fund();vm.prank(recipient);e.claim(id,recipient,sig(e.claimAuthorizationDigest(id,recipient),recipientPk));BaseEscrow.Terms memory t=e.terms(id);require(uint(t.state)==2&&recipient.balance==1 ether);}
 function testWrongSignatureAndReplay() public {setUp();bytes memory bad=sig(e.fundAuthorizationDigest(id),recipientPk);bool failed;try e.fund{value:1 ether}(id,bad) {} catch {failed=true;}require(failed);fund();bytes memory good=sig(e.fundAuthorizationDigest(id),payerPk);failed=false;try e.fund{value:1 ether}(id,good) {} catch {failed=true;}require(failed);}
 function testBoundaryAndRefundOnlyDestination() public {setUp();fund();vm.warp(block.timestamp+100);bool failed;try e.claim(id,recipient,sig(e.claimAuthorizationDigest(id,recipient),recipientPk)) {} catch {failed=true;}require(failed);failed=false;try e.refund(id) {} catch {failed=true;}require(failed);vm.prank(refund);e.refund(id);require(uint(e.terms(id).state)==3);}
 function testClaimBeforeExpiryBeatsRefund() public {setUp();fund();vm.prank(recipient);e.claim(id,recipient,sig(e.claimAuthorizationDigest(id,recipient),recipientPk));vm.prank(refund);vm.expectRevert(BaseEscrow.WrongState.selector);e.refund(id);}
 function testWrongClaimTermsAndRecipient() public {setUp();fund();address other=vm.addr(0xDAD);bool failed;try e.claim(id,other,sig(e.claimAuthorizationDigest(id,recipient),recipientPk)) {} catch {failed=true;}require(failed);}
 function testTokenExactAndFeeRejected() public {MockToken t=new MockToken();ERC20Escrow x=new ERC20Escrow(address(t));t.mint(payer,5);vm.prank(payer);t.approve(address(x),1);vm.prank(payer);x.createTerms(id,refund,commitment,1,block.timestamp+100,7);vm.prank(payer);x.fund(id,sig(x.fundAuthorizationDigest(id),payerPk));require(t.balanceOf(address(x))==1);}
 function testTokenFeeOnTransferRejected() public {MockToken t=new MockToken();ERC20Escrow x=new ERC20Escrow(address(t));t.mint(payer,5);t.setFee(true);vm.prank(payer);t.approve(address(x),1);vm.prank(payer);x.createTerms(id,refund,commitment,1,block.timestamp+100,7);bool failed;try x.fund(id,sig(x.fundAuthorizationDigest(id),payerPk)) {} catch {failed=true;}require(failed);}
 function testDuplicateCreateWrongEthAndClaimReplay() public {setUp();bool failed;try e.createTerms(id,refund,commitment,1,block.timestamp+200,8) {} catch {failed=true;}require(failed);bytes memory approval=sig(e.fundAuthorizationDigest(id),payerPk);failed=false;try e.fund{value:2 ether}(id,approval) {} catch {failed=true;}require(failed);fund();bytes memory authorization=sig(e.claimAuthorizationDigest(id,recipient),recipientPk);vm.prank(recipient);e.claim(id,recipient,authorization);failed=false;try e.claim(id,recipient,authorization) {} catch {failed=true;}require(failed);}
 function testTokenFalseReturnRejected() public {MockToken t=new MockToken();ERC20Escrow x=new ERC20Escrow(address(t));t.mint(payer,5);vm.prank(payer);t.approve(address(x),1);vm.prank(payer);x.createTerms(id,refund,commitment,1,block.timestamp+100,7);t.setFail(true);bool failed;try x.fund(id,sig(x.fundAuthorizationDigest(id),payerPk)) {} catch {failed=true;}require(failed);}
}
